name: dbt CI

on:
  pull_request:
    branches: [main]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: .
      PR_SCHEMA: dbt_pr_${{ github.event.pull_request.number }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-snowflake

      - name: Create profiles.yml
        run: |
          cat <<EOF > profiles.yml
          snowflake_dbt_demo2:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: ${PR_SCHEMA}
                threads: 4
          EOF

      - name: Install dependencies
        run: dbt deps

      - name: Debug connection
        run: dbt debug

      # Download production manifest (for defer/state)
      - name: Download production manifest
        uses: actions/download-artifact@v4
        with:
          name: prod-manifest
          path: state
        continue-on-error: true

      - name: Run dbt build for modified models
        run: |
          dbt build \
            --select state:modified+ \
            --defer \
            --state state

      - name: Cleanup CI schema
        if: always()
        run: |
          pip install snowflake-connector-python
          python - <<EOF
          import snowflake.connector
          import os

          conn = snowflake.connector.connect(
              user=os.environ["SNOWFLAKE_USER"],
              password=os.environ["SNOWFLAKE_PASSWORD"],
              account=os.environ["SNOWFLAKE_ACCOUNT"],
              warehouse=os.environ["SNOWFLAKE_WAREHOUSE"],
              database=os.environ["SNOWFLAKE_DATABASE"],
              role=os.environ["SNOWFLAKE_ROLE"],
          )

          schema = os.environ["PR_SCHEMA"]

          cs = conn.cursor()
          cs.execute(f"DROP SCHEMA IF EXISTS {schema}")
          cs.close()
          conn.close()
          EOF